-- ============================================================
-- Seed: catalogo de ingredientes (user_id null = global)
-- ============================================================
-- 121 ingredientes de supermercado chileno con los puentes de conversion
-- ya cargados. Es el trabajo aburrido que hace que la lista de compras
-- funcione: sin densidad_g_ml no puedes sumar "1 taza de harina" con
-- "200 g de harina", y sin peso_unidad_g no puedes sumar "3 tomates"
-- con "400 g de tomate".
--
-- Los valores son aproximados y estan pensados para editarse: si compras
-- tomates mas grandes, cambia peso_unidad_g y la lista se ajusta sola.
-- ============================================================

insert into ingredientes
  (slug, nombre, pasillo, base, densidad_g_ml, peso_unidad_g, pack_base, es_basico)
values
  ('tomate', 'Tomate', 'verduleria', 'g', 0.95, 150, 500, false),
  ('cebolla', 'Cebolla', 'verduleria', 'g', null, 170, 1000, false),
  ('ajo', 'Ajo', 'verduleria', 'un', null, 5, 10, true),
  ('papa', 'Papa', 'verduleria', 'g', null, 180, 1000, false),
  ('zanahoria', 'Zanahoria', 'verduleria', 'g', null, 80, 500, false),
  ('zapallo-italiano', 'Zapallo italiano', 'verduleria', 'g', null, 200, 200, false),
  ('zapallo', 'Zapallo camote', 'verduleria', 'g', null, null, 1000, false),
  ('pimenton-rojo', 'Pimenton rojo', 'verduleria', 'g', null, 160, 160, false),
  ('pimenton-verde', 'Pimenton verde', 'verduleria', 'g', null, 150, 150, false),
  ('lechuga', 'Lechuga', 'verduleria', 'un', null, 400, 1, false),
  ('cilantro', 'Cilantro (atado)', 'verduleria', 'un', null, 40, 1, false),
  ('perejil', 'Perejil (atado)', 'verduleria', 'un', null, 40, 1, false),
  ('cebollin', 'Cebollin (atado)', 'verduleria', 'un', null, 60, 1, false),
  ('palta', 'Palta', 'verduleria', 'un', null, 200, 1, false),
  ('limon', 'Limon', 'verduleria', 'un', null, 90, 1, false),
  ('choclo', 'Choclo', 'verduleria', 'un', null, 300, 1, false),
  ('porotos-verdes', 'Porotos verdes', 'verduleria', 'g', null, null, 500, false),
  ('espinaca', 'Espinaca', 'verduleria', 'g', null, null, 300, false),
  ('brocoli', 'Brocoli', 'verduleria', 'g', null, 400, 400, false),
  ('champinon', 'Champinones', 'verduleria', 'g', null, 20, 200, false),
  ('apio', 'Apio', 'verduleria', 'un', null, 400, 1, false),
  ('betarraga', 'Betarraga', 'verduleria', 'g', null, 150, 500, false),
  ('aji-verde', 'Aji verde', 'verduleria', 'un', null, 20, 1, false),
  ('repollo', 'Repollo', 'verduleria', 'g', null, 900, 900, false),
  ('platano', 'Platano', 'verduleria', 'un', null, 120, 1, false),
  ('manzana', 'Manzana', 'verduleria', 'un', null, 180, 1, false),
  ('naranja', 'Naranja', 'verduleria', 'un', null, 200, 1, false),
  ('frutilla', 'Frutillas', 'verduleria', 'g', null, null, 250, false),
  ('pollo-entero', 'Pollo entero', 'carniceria', 'g', null, 1800, 1800, false),
  ('pechuga-pollo', 'Pechuga de pollo', 'carniceria', 'g', null, 200, 500, false),
  ('trutro-pollo', 'Trutro de pollo', 'carniceria', 'g', null, 150, 1000, false),
  ('carne-molida', 'Carne molida', 'carniceria', 'g', null, null, 500, false),
  ('posta-rosada', 'Posta rosada', 'carniceria', 'g', null, null, 1000, false),
  ('lomo-liso', 'Lomo liso', 'carniceria', 'g', null, null, 1000, false),
  ('asado-de-tira', 'Asado de tira', 'carniceria', 'g', null, null, 1000, false),
  ('chuleta-cerdo', 'Chuleta de cerdo', 'carniceria', 'g', null, 180, 1000, false),
  ('longaniza', 'Longaniza', 'carniceria', 'un', null, 100, 5, false),
  ('salchicha', 'Salchicha', 'carniceria', 'un', null, 45, 6, false),
  ('tocino', 'Tocino', 'carniceria', 'g', null, null, 200, false),
  ('jamon', 'Jamon', 'carniceria', 'g', null, null, 200, false),
  ('merluza', 'Merluza', 'carniceria', 'g', null, null, 500, false),
  ('salmon', 'Salmon', 'carniceria', 'g', null, null, 300, false),
  ('reineta', 'Reineta', 'carniceria', 'g', null, null, 500, false),
  ('leche', 'Leche', 'lacteos', 'ml', 1.03, null, 1000, false),
  ('yogur', 'Yogur natural', 'lacteos', 'g', 1.03, 125, 1000, false),
  ('mantequilla', 'Mantequilla', 'lacteos', 'g', 0.91, null, 250, true),
  ('margarina', 'Margarina', 'lacteos', 'g', 0.9, null, 250, false),
  ('queso-gauda', 'Queso gauda', 'lacteos', 'g', null, 20, 250, false),
  ('queso-mantecoso', 'Queso mantecoso', 'lacteos', 'g', null, null, 250, false),
  ('queso-crema', 'Queso crema', 'lacteos', 'g', 1.05, null, 180, false),
  ('crema', 'Crema', 'lacteos', 'ml', 1.0, null, 200, false),
  ('quesillo', 'Quesillo', 'lacteos', 'g', null, 200, 200, false),
  ('leche-condensada', 'Leche condensada', 'lacteos', 'g', 1.28, null, 397, false),
  ('parmesano', 'Parmesano rallado', 'lacteos', 'g', 0.42, null, 100, false),
  ('pan-molde', 'Pan de molde', 'panaderia', 'un', null, 28, 20, false),
  ('hallulla', 'Hallulla', 'panaderia', 'un', null, 100, 1, false),
  ('marraqueta', 'Marraqueta', 'panaderia', 'un', null, 100, 1, false),
  ('pan-amasado', 'Pan amasado', 'panaderia', 'un', null, 90, 1, false),
  ('tortilla', 'Tortilla de trigo', 'panaderia', 'un', null, 40, 8, false),
  ('arroz', 'Arroz', 'abarrotes', 'g', 0.85, null, 1000, false),
  ('tallarines', 'Tallarines', 'abarrotes', 'g', null, null, 400, false),
  ('espirales', 'Espirales', 'abarrotes', 'g', null, null, 400, false),
  ('lentejas', 'Lentejas', 'abarrotes', 'g', 0.85, null, 500, false),
  ('porotos', 'Porotos', 'abarrotes', 'g', 0.8, null, 500, false),
  ('garbanzos', 'Garbanzos', 'abarrotes', 'g', 0.8, null, 500, false),
  ('quinoa', 'Quinoa', 'abarrotes', 'g', 0.75, null, 500, false),
  ('avena', 'Avena', 'abarrotes', 'g', 0.4, null, 500, false),
  ('harina', 'Harina', 'abarrotes', 'g', 0.53, null, 1000, true),
  ('azucar', 'Azucar', 'abarrotes', 'g', 0.85, null, 1000, true),
  ('sal', 'Sal', 'abarrotes', 'g', 1.2, null, 1000, true),
  ('aceite', 'Aceite vegetal', 'abarrotes', 'ml', 0.92, null, 900, true),
  ('aceite-oliva', 'Aceite de oliva', 'abarrotes', 'ml', 0.91, null, 500, false),
  ('vinagre', 'Vinagre', 'abarrotes', 'ml', 1.01, null, 500, true),
  ('salsa-tomate', 'Salsa de tomate', 'abarrotes', 'g', 1.03, null, 200, false),
  ('pasta-tomate', 'Pasta de tomate', 'abarrotes', 'g', 1.1, null, 70, false),
  ('tomate-conserva', 'Tomate en conserva', 'abarrotes', 'g', 1.03, null, 400, false),
  ('huevo', 'Huevo', 'abarrotes', 'un', null, 60, 12, false),
  ('caldo-cubo', 'Caldo en cubo', 'abarrotes', 'un', null, 10, 8, true),
  ('comino', 'Comino', 'abarrotes', 'g', 0.45, null, 20, true),
  ('oregano', 'Oregano', 'abarrotes', 'g', 0.2, null, 20, true),
  ('paprika', 'Paprika', 'abarrotes', 'g', 0.45, null, 20, true),
  ('pimienta', 'Pimienta', 'abarrotes', 'g', 0.5, null, 20, true),
  ('aji-color', 'Aji de color', 'abarrotes', 'g', 0.45, null, 20, true),
  ('merken', 'Merken', 'abarrotes', 'g', 0.4, null, 20, false),
  ('canela', 'Canela', 'abarrotes', 'g', 0.45, null, 20, true),
  ('polvos-hornear', 'Polvos de hornear', 'abarrotes', 'g', 0.7, null, 100, true),
  ('levadura', 'Levadura seca', 'abarrotes', 'g', 0.68, null, 10, false),
  ('maicena', 'Maicena', 'abarrotes', 'g', 0.6, null, 250, false),
  ('mostaza', 'Mostaza', 'abarrotes', 'ml', 1.05, null, 250, false),
  ('mayonesa', 'Mayonesa', 'abarrotes', 'g', 0.94, null, 500, false),
  ('salsa-soya', 'Salsa de soya', 'abarrotes', 'ml', 1.15, null, 300, false),
  ('miel', 'Miel', 'abarrotes', 'ml', 1.4, null, 500, false),
  ('nueces', 'Nueces', 'abarrotes', 'g', 0.5, null, 200, false),
  ('almendras', 'Almendras', 'abarrotes', 'g', 0.55, null, 200, false),
  ('pasas', 'Pasas', 'abarrotes', 'g', 0.65, null, 250, false),
  ('cacao', 'Cacao amargo', 'abarrotes', 'g', 0.5, null, 150, false),
  ('atun', 'Atun en tarro', 'abarrotes', 'g', null, 160, 160, false),
  ('aceitunas', 'Aceitunas', 'abarrotes', 'g', null, null, 200, false),
  ('choclo-conserva', 'Choclo en conserva', 'abarrotes', 'g', null, null, 300, false),
  ('arvejas-conserva', 'Arvejas en conserva', 'abarrotes', 'g', null, null, 300, false),
  ('galletas-soda', 'Galletas de soda', 'abarrotes', 'g', null, null, 300, false),
  ('cafe', 'Cafe', 'abarrotes', 'g', 0.4, null, 170, true),
  ('te', 'Te (bolsitas)', 'abarrotes', 'un', null, 2, 20, true),
  ('arvejas-congeladas', 'Arvejas congeladas', 'congelados', 'g', 0.7, null, 400, false),
  ('papas-fritas-cong', 'Papas fritas congeladas', 'congelados', 'g', null, null, 1000, false),
  ('verduras-salteadas', 'Verduras salteadas congeladas', 'congelados', 'g', null, null, 400, false),
  ('camaron', 'Camarones', 'congelados', 'g', null, 8, 500, false),
  ('masa-hojas', 'Masa de hojas', 'congelados', 'g', null, null, 400, false),
  ('helado', 'Helado', 'congelados', 'ml', null, null, 1000, false),
  ('agua-mineral', 'Agua mineral', 'bebidas', 'ml', 1.0, null, 1500, false),
  ('bebida', 'Bebida', 'bebidas', 'ml', 1.03, null, 1500, false),
  ('jugo', 'Jugo', 'bebidas', 'ml', 1.03, null, 1000, false),
  ('vino', 'Vino', 'bebidas', 'ml', 0.99, null, 750, false),
  ('cerveza', 'Cerveza', 'bebidas', 'ml', 1.01, null, 350, false),
  ('detergente', 'Detergente de ropa', 'limpieza', 'ml', 1.05, null, 3000, false),
  ('lavalozas', 'Lavalozas', 'limpieza', 'ml', 1.03, null, 750, false),
  ('cloro', 'Cloro', 'limpieza', 'ml', 1.08, null, 900, false),
  ('papel-confort', 'Papel confort', 'limpieza', 'un', null, null, 12, false),
  ('toalla-papel', 'Toalla de papel', 'limpieza', 'un', null, null, 3, false),
  ('bolsa-basura', 'Bolsas de basura', 'limpieza', 'un', null, null, 20, false),
  ('esponja', 'Esponja', 'limpieza', 'un', null, null, 3, false)
on conflict (user_id, slug) do update set
  nombre        = excluded.nombre,
  pasillo       = excluded.pasillo,
  base          = excluded.base,
  densidad_g_ml = excluded.densidad_g_ml,
  peso_unidad_g = excluded.peso_unidad_g,
  pack_base     = excluded.pack_base,
  es_basico     = excluded.es_basico;
